//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IFooter, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cta Button
		///</summary>
		[ImplementPropertyType("ctaButton")]
		public string CtaButton
		{
			get { return this.GetPropertyValue<string>("ctaButton"); }
		}

		///<summary>
		/// Header Title
		///</summary>
		[ImplementPropertyType("headerTitle")]
		public string HeaderTitle
		{
			get { return this.GetPropertyValue<string>("headerTitle"); }
		}

		///<summary>
		/// Sub Heading
		///</summary>
		[ImplementPropertyType("subHeading")]
		public string SubHeading
		{
			get { return this.GetPropertyValue<string>("subHeading"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetDescription(this); }
		}

		///<summary>
		/// Input
		///</summary>
		[ImplementPropertyType("input")]
		public string Input
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetInput(this); }
		}

		///<summary>
		/// Left Title
		///</summary>
		[ImplementPropertyType("leftTitle")]
		public string LeftTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetLeftTitle(this); }
		}

		///<summary>
		/// Middle Title
		///</summary>
		[ImplementPropertyType("middleTitle")]
		public string MiddleTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetMiddleTitle(this); }
		}

		///<summary>
		/// Right Title
		///</summary>
		[ImplementPropertyType("rightTitle")]
		public string RightTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Footer.GetRightTitle(this); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMenuTitle(this); }
		}
	}
}
